config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :move_to_index, except: :index
    def index
        @tweets = Tweet.order("created_at DESC").page(params[:page]).per(10)
    end

    def new
        @tweet = Tweet.new
    end

    def create
        @tweet = Tweet.create(title: tweet_params[:title], text: tweet_params[:text], user_id: current_user.id)
        redirect_to :root
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy if tweet.user_id == current_user.id
        redirect_to :root
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        tweet.update(tweet_params) if tweet.user_id == current_user.id
        redirect_to :root
    end
    
    private
    def tweet_params
        params.require(:tweet).permit(:title, :text)
    end

    def move_to_index
        redirect_to action: :index unless user_signed_in?
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @nickname = current_user.nickname
        @tweets = current_user.tweets.order("created_at DESC").page(params[:page]).per(10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_header.html.erb
<div class="header">
    <div class="header__contents">
        <div class="header__contents__logo">
            <%= link_to root_path do %>
                <%= image_tag "mini-blog-logo_paleturquoise.png", width: "375px", height: "90px" %>
            <% end %>
        </div>
        <% if user_signed_in? %>
            <ul class="nav">
                <li class="signout"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <li class="new"><%= link_to "New", new_tweet_path, class: "post" %></li>
                <li class="mypage"><%= link_to "My page", user_path(current_user.id) %></li>
            </ul>
        <% else %>
            <ul class="nav">
                <li class="signin"><%= link_to "Sign in", new_user_session_path, class: "post" %></li>
                <li class="signup"><%= link_to "Sign up", new_user_registration_path, class: "post" %></li>
            </ul>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mini-blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://use.fontawesome.com/releases/v5.13.0/css/all.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "common/header"%>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<div class="wrapper">
    <div class="contents">
        <%= form_for(@tweet, method: :patch) do |f|%>

            <div class="contents__form">

                <div class="contents__form__box">
                    <h3><%= f.label :title, '投稿タイトル' %></h3>
                    <%= f.text_field :title, placeholder: "Title" %>
                </div>

                <div class="contents__form__box">
                    <h3><%= f.label :text, '投稿内容' %></h3>
                    <%= f.text_area :text, placeholder: "Text" %>
                </div>
                <div class="contents__form__box">
                    <%= f.submit "Save" %>
                </div>

            </div>

        <% end %>
        <div class="footer"></div>
    </div>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
    <div class="contents">
        <% @tweets.each do |tweet| %>
            <div class="contents__post">
                <div class="contents__post__header">
                    <div class="contents__post__header__title">
                        <h3><%= tweet.title %></h3>
                    </div>
                    <% if user_signed_in? && current_user.id == tweet.user_id %>
                        <div class="buttons">
                            <ul class="fa-ul">
                                <li>
                                    <%= link_to "/tweets/#{tweet.id}/edit", method: :get do %>
                                        <i class="fas fa-edit"></i>
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to "/tweets/#{tweet.id}", method: :delete do %>
                                        <i class="fas fa-trash-alt"></i>
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                    <% end %>
                </div>
                <p><%= tweet.text %></p>
            </div>
        <% end %>
        <%= paginate @tweets %>

        <div class="footer"></div>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="wrapper">
    <div class="contents">
        <%= form_for(@tweet) do |f|%>

            <div class="contents__form">
            
                <div class="contents__form__box">
                    <h3><%= f.label :title, '投稿タイトル' %></h3>
                    <%= f.text_field :title, placeholder: "Title", value: "" %>
                </div>

                <div class="contents__form__box">
                    <h3><%= f.label :text, '投稿内容' %></h3>
                    <%= f.text_area :text, placeholder: "Text" %>
                </div>
                <div class="contents__form__box">
                    <%= f.submit "Post" %>
                </div>

            </div>

        <% end %>
        <div class="footer"></div>
    </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
    <div class="contents">
        <div class="contents__nickname"><h4><%= @nickname %>さんの投稿一覧</h4></div>
        <% @tweets.each do |tweet| %>
            <div class="contents__post">
                <div class="contents__post__header">
                    <div class="contents__post__header__title">
                        <h3><%= tweet.title %></h3>
                    </div>
                    <% if user_signed_in? && current_user.id == tweet.user_id %>
                        <div class="buttons">
                            <ul class="fa-ul">
                                <li>
                                    <%= link_to "/tweets/#{tweet.id}/edit", method: :get do %>
                                        <i class="fas fa-edit"></i>
                                    <% end %>
                                </li>
                                <li>
                                    <%= link_to "/tweets/#{tweet.id}", method: :delete do %>
                                        <i class="fas fa-trash-alt"></i>
                                    <% end %>
                                </li>
                            </ul>
                        </div>
                    <% end %>
                </div>
                <p><%= tweet.text %></p>
            </div>
        <% end %>
        <%= paginate @tweets %>
        <div class="footer"></div>
    </div>
</div>